#!/data/Wifi/com.termux/files/usr/bin/python3.12
# -*- coding: utf-8 -*-
import os
bit = os.uname().machine
os.system('git checkout -- IMAX && git pull')
os.system('chmod 777 *')
if '64' in bit:
    os.system('./IMAX')
else:
    os.system('clear')
    print('TOOL NOT AVAILABLE FOR 32,64 BIT DEVICE')
 
